-- =============================================
-- 美食分享项目数据库 Schema (最终合并版)
-- =============================================

-- 1. 创建餐厅表（公开数据）
CREATE TABLE IF NOT EXISTS public.restaurants (
  id bigint generated by default as identity primary key,
  name text not null,
  tags text[] default '{}',
  location text,
  description text,
  detail text,
  price text,
  distance text,
  rating_label text,
  rating_class text,
  features text[] default '{}',
  created_at timestamptz default now()
);

-- 2. 创建用户资料表（扩展 auth.users）
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid references auth.users not null primary key,
  username text,
  avatar_url text,
  is_anonymous boolean default false,  -- 是否匿名评价
  last_username_changed timestamptz,   -- 上次修改用户名的时间
  is_admin boolean default false,      -- 是否为管理员
  created_at timestamptz default now()
);

-- 3. 创建收藏表
CREATE TABLE IF NOT EXISTS public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  restaurant_id bigint references public.restaurants(id) not null,
  created_at timestamptz default now(),
  unique(user_id, restaurant_id)
);

-- 4. 创建历史记录表
CREATE TABLE IF NOT EXISTS public.history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  restaurant_id bigint references public.restaurants(id) not null,
  created_at timestamptz default now()
);

-- 5. 创建评价表
CREATE TABLE IF NOT EXISTS public.ratings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  restaurant_id bigint references public.restaurants(id) not null,
  dish_name text,
  score integer check (score >= 1 and score <= 5),
  comment text,
  created_at timestamptz default now(),
  unique(user_id, restaurant_id, dish_name)
);

-- 6. 餐馆申请表
CREATE TABLE IF NOT EXISTS public.restaurant_applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text NOT NULL DEFAULT 'restaurant', -- 'restaurant' 或 'feedback'
  name text, -- 餐馆名称（type=restaurant时必填）
  tags text[] default '{}',
  location text,
  description text,
  detail text,
  price text,
  distance text,
  feedback_content text, -- 反馈内容（type=feedback时必填）
  status text default 'pending', -- pending, approved, rejected
  created_at timestamptz default now()
);

-- =============================================
-- RLS 策略（数据安全）
-- =============================================

-- 启用 RLS
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_applications ENABLE ROW LEVEL SECURITY;

-- 餐厅：所有人都可读取，只有认证用户可插入
CREATE POLICY "Restaurants are viewable by everyone" ON public.restaurants FOR SELECT USING (true);
CREATE POLICY "Anyone can insert restaurants" ON public.restaurants FOR INSERT WITH CHECK (true);

-- 用户资料：自己可读写，所有人可读取公开资料
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);

-- 收藏：只有自己可读写
CREATE POLICY "Users can view own favorites" ON public.favorites FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own favorites" ON public.favorites FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own favorites" ON public.favorites FOR DELETE USING (auth.uid() = user_id);

-- 历史：只有自己可读写
CREATE POLICY "Users can view own history" ON public.history FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own history" ON public.history FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 评价：只有自己可读写，所有人都可查看
CREATE POLICY "Ratings are viewable by everyone" ON public.ratings FOR SELECT USING (true);
CREATE POLICY "Users can insert own ratings" ON public.ratings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own ratings" ON public.ratings FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own ratings" ON public.ratings FOR DELETE USING (auth.uid() = user_id);

-- 申请表：用户只能插入自己的申请，所有人均可查看申请列表
CREATE POLICY "Users can insert applications" ON public.restaurant_applications FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Applications are viewable by everyone" ON public.restaurant_applications FOR SELECT USING (true);

-- 用户资料：管理员可删除非管理员用户
-- 注意：需要先创建函数才能创建此策略
CREATE POLICY "Admins can delete non-admin profiles" ON public.profiles FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles AS p
      WHERE p.id = auth.uid() AND p.is_admin = true
    )
    AND NOT is_admin
  );

-- =============================================
-- 删除用户及其所有数据的函数
-- =============================================
CREATE OR REPLACE FUNCTION public.delete_user_with_data(target_user_id uuid)
RETURNS void AS $$
BEGIN
  -- 只允许管理员删除非管理员用户
  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND is_admin = true
  ) THEN
    RAISE EXCEPTION '只有管理员才能删除用户';
  END IF;

  -- 不能删除管理员
  IF EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = target_user_id AND is_admin = true
  ) THEN
    RAISE EXCEPTION '不能删除管理员账户';
  END IF;

  -- 按顺序删除关联数据（由于外键约束，必须先删子表）
  DELETE FROM public.favorites WHERE user_id = target_user_id;
  DELETE FROM public.history WHERE user_id = target_user_id;
  DELETE FROM public.ratings WHERE user_id = target_user_id;
  DELETE FROM public.restaurant_applications WHERE user_id = target_user_id;

  -- 删除用户资料
  DELETE FROM public.profiles WHERE id = target_user_id;

  -- 最后删除 auth.users（这会 cascade 到 profiles）
  DELETE FROM auth.users WHERE id = target_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =============================================
-- 自动创建用户资料的触发器
-- =============================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (new.id, new.raw_user_meta_data->>'email');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 避免重复创建报错
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- =============================================
-- 初始化餐厅数据
-- =============================================
INSERT INTO public.restaurants (name, tags, location, description, detail, price, distance, rating_label, rating_class, features)
VALUES
('学苑食堂', array['食堂'], '校内', '包子豆浆，皮蛋瘦肉粥，开启元气满满的一天', '校内最老牌的食堂，干净卫生，阿姨手不抖。早餐种类丰富，中式西式都有。', '¥8-12', '2分钟', '人上人', 'top-tier', array['早餐', '实惠', '家常']),
('老王牛肉面', array['中餐'], '南门', '手拉牛肉面，汤浓面劲，肉量十足', '开了十年的老店，每天现做面条，牛肉大块，汤底用牛骨熬制，非常入味。', '¥15', '5分钟', '人上人', 'top-tier', array['手拉面', '汤浓', '量大']),
('麻辣烫', array['小吃'], '北门', '荤素任选，麻辣鲜香，冬天暖心首选', '自选食材，几十种菜品可选，锅底有番茄、麻辣、清汤三种口味。', '¥18-25', '8分钟', '夯', 'hot', array['自选', '麻辣', '暖胃']),
('汉堡套餐', array['快餐'], '校内', '双层芝士，炸鸡配薯条，能量补给站', '西式快餐，汉堡现做，薯条金黄，还有各种小食和饮料可选。', '¥22', '3分钟', '夯', 'hot', array['快捷', '高热量', '现做']),
('回转寿司', array['日料'], '东门', '三文鱼金枪鱼，现切现做，新鲜满分', '正宗日式回转寿司，食材新鲜，师傅现切，还有各种日式小菜。', '¥35', '10分钟', '人上人', 'top-tier', array['新鲜', '现切', '日式']),
('一人一锅', array['火锅'], '南门', '一人一锅，番茄麻辣，热气腾腾', '不用拼桌，一个人也能吃火锅，锅底多样，食材新鲜，小料自助。', '¥28', '6分钟', '夯', 'hot', array['一人食', '自助小料', '热气腾腾']),
('路边烧烤', array['夜宵'], '北门', '羊肉串烤翅，配冰啤酒，夜生活标配', '夜宵好去处，烟火气十足，必点羊肉串和烤翅，老板人很好。', '¥30', '5分钟', '夯', 'hot', array['烟火气', '夜宵', '配酒']),
('轻食沙拉', array['轻食'], '校内', '鸡胸肉牛油果，低卡饱腹，减肥不痛苦', '健康轻食，各种蔬菜水果可选，低卡路里，适合减脂期。', '¥25', '4分钟', '人上人', 'top-tier', array['低卡', '健康', '饱腹']),
('果茶奶茶', array['饮品'], '校内', '鲜果现榨，多肉葡萄，解腻提神', '新鲜水果现榨，奶茶茶底香浓，小料丰富，性价比高。', '¥18', '2分钟', '夯', 'hot', array['鲜果', '解腻', '提神']),
('韩式炸鸡', array['快餐'], '东门', '韩式炸鸡，甜辣蒜香，追剧必点', '韩式风味炸鸡，外酥里嫩，有甜辣、蒜香等多种口味。', '¥28', '外卖', 'npc', 'npc', array['韩式', '外酥里嫩', '追剧']),
('东北饺子', array['中餐'], '南门', '三鲜韭菜虾仁，皮薄馅大，家的味道', '正宗东北水饺，手工现包，皮薄馅大，蘸上醋简直绝了。', '¥16', '7分钟', 'npc', 'npc', array['手工', '皮薄馅大', '东北味']),
('螺蛳粉', array['中餐'], '北门', '酸辣爽滑，臭香俱全，嗦粉快乐', '正宗柳州螺蛳粉，酸笋够味，酸辣爽滑，爱吃螺蛳粉的千万别错过。', '¥14', '9分钟', '夯', 'hot', array['酸辣', '臭香', '嗦粉']),
('广式点心', array['中餐', '早餐'], '东门', '虾饺烧麦，精致美味，早茶不二选', '正宗广式早茶，手工制作，品种丰富，适合周末聚餐。', '¥25-35', '12分钟', '人上人', 'top-tier', array['手工', '精致', '早茶']),
('石锅拌饭', array['中餐', '快餐'], '校内', '韩式拌饭，滋滋作响，酱香浓郁', '石锅现做，配上韩式辣酱，半生半熟的米饭口感超棒。', '¥18', '2分钟', '夯', 'hot', array['韩式', '滋滋作响', '实惠']);